### ISSUE TITLE
Increase the size of the area selector

### ISSUE THREAD

**Issue by r0nz-29** [sysoppl/Cities-Skylines-heightmap-generator#12] opened 2021-07-16 17:14 UTC
How do I resize the selector square to cover more area

**Comment by sysoppl** [comment] 2021-07-17 09:02
This is not possible now, also duplicate of https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/10

**Closed by sysoppl** 2021-07-17 09:02 UTC
