### ISSUE TITLE
Heightmap bigger than the selected area

### ISSUE THREAD

**Issue by svbtext** [sysoppl/Cities-Skylines-heightmap-generator#11] opened 2021-07-14 20:40 UTC
First off, I just wanna say thank you so much for making this tool now that terrain party seems to be down for good.

Anyway, I've been having an issue with the downloaded heightmap's area being significantly larger than the area I select in the map. Here's an example of what I mean, you can see it pretty clearly with the lake on the left.

![example](https://user-images.githubusercontent.com/10595675/125688071-a6fe22a8-0e86-4920-8070-a6333c8eee29.png)

Obviously this isn't a major bug but I like to screenshot the selected area on the map and use that as a basis for making an in-game overlay, and it's a bit annoying having to try and guess how much to resize it to get everything lined up right. It'd be much appreciated if you could fix it somehow!

**Comment by sysoppl** [comment] 2021-07-17 09:01
Hey, this is duplicate of https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/3

**Closed by sysoppl** 2021-07-17 09:01 UTC
